# Use the official OpenJDK 17 image as the base image
FROM openjdk:17-jdk-slim

# Add a volume to store temporary files
VOLUME /tmp

# Copy the built JAR file from the target directory
COPY ./target/user-service-0.0.1-SNAPSHOT.jar user-service.jar

# Expose the application port
EXPOSE 8081

# Command to run the Spring Boot application
ENTRYPOINT ["java", "-jar", "/user-service.jar"]
